### ISSUE TITLE
JWT gets 24 hour lifetime and remove password from frontend

### ISSUE THREAD

**Issue by theErikss0n** [matekasse/matekasse#16]
implement jwt refresh tokens, so the user password does not have to be saved on the client to refresh the jwt.

**Comment by neilschark** [comment]
After talking to @andresterba we agreed on initially increase the lifetime of a jwt token to 24 hours and not use a refresh token. But also the storage of the password will be removed in frontend. The refresh token gets a new issue but not for release 0.1.0.
