### ISSUE TITLE
The username is displayed very small in the user settings

### ISSUE THREAD

**Issue by andresterba** [matekasse/matekasse#174]
![2021-09-18-204428_grim](https://user-images.githubusercontent.com/48120735/133905418-6161aab0-3664-49f7-bd89-5af023b0fc3b.png)

**Comment by Sanket2055** [comment]
hello sir , is this issue still open , i would like to contribute please assign me this task

**Comment by neilschark** [comment]
@Sanket2055 Thanks, but the Issue is already work in progress https://github.com/matekasse/matekasse/pull/211

But feel free to open a pr to another image.
