### ISSUE TITLE
Addition of money should be green instead of yellow

### ISSUE THREAD

**Issue by andresterba** [matekasse/matekasse#180]
![2021-09-20-195348_grim](https://user-images.githubusercontent.com/48120735/134050526-5324b546-1f4d-441a-b1df-91d89cacce8c.png)

**Comment by andresterba** [comment]
Actually storno is green, topUp yellow and order red.
Lets make topUp and storno green? @theErikss0n @neilschark 

![2021-09-20-204640_grim](https://user-images.githubusercontent.com/48120735/134065291-15050f5a-effd-4daa-a296-ffe94eb47d8e.png)

**Comment by neilschark** [comment]
i think topUp and storno should be a different colour, to better differentiate between them.

**Comment by andresterba** [comment]
But why?
Both add something to your account.
We also have the type filters...
