### ISSUE TITLE
Set sane default admin credentials

### ISSUE THREAD

**Issue by theErikss0n** [matekasse/matekasse#43]
Set default admin credentials to
username: admin
password: admin

**Comment by neilschark** [comment]
All our system users and also the admin user use upper case names, so that it looks better on the webpage. We could only change the Admins name to lower case and keep the rest, but it will look a bit weird.

**Comment by neilschark** [comment]
Suggestion: we just make the username case insensitive. That means we can keep the uppercase names but you can always log in, etc with just lowercase names.
