### ISSUE TITLE
Cannot create warehouse transaction for second newly created product

### ISSUE THREAD

**Issue by theErikss0n** [matekasse/matekasse#48]
Steps to reproduce:
1. Create new product
2. Create second product
3. Try to create a new warehouse transaction for second product

Second product is not shown in dropdown menu until refreshing the page.

**Comment by andresterba** [comment]
The problem is that the `create-warehouse-transaction-modal` only calls `loadProducts()` when it is created.
So the actual steps to reproduce this are:

	1. Open the warehouse transactions tab
    2. Create new product
    3. Create second product
    4. Try to create a new warehouse transaction for second product

All created products are not available in the warehouse transactions tab.
