### ISSUE TITLE
Can't create a new tag when creating/editing a product if a similar tag exists

### ISSUE THREAD

**Issue by neilschark** [matekasse/matekasse#96]
Right now its not possible to create a new tag, if a similar named tag already exists. 

E.g.:

The tag "alcohol-free" already exists and I want to create the tag "alcohol" it's not possible, because the modal suggests to use "alcohol-free". There is no way to create this new tag.

**Comment by theErikss0n** [comment]
Manufacturers have the same problem. We should fix this here
